version: "3.5"

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  data: {}