server:
  port: 8070

spring:
  mvc:
    servlet:
      path: /api
  datasource:
    url: jdbc:postgresql://db:5432/ippo
    username: ippo
    password: ippo
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true


logging:
  level:
    org.hibernate.SQL: DEBUG
    or.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
